[build-system]
requires = [
    "setuptools>=61",
]
build-backend = "setuptools.build_meta"

[project]
name = "pygeostat"
dynamic = ["dependencies", "version"]
authors = [
    {name = "Jared Deutsch"},
    {name = "Matthew Deutsch"},
    {name = "Ryan Martin"},
    {name = "Warren Black"},
    {name = "Tyler Acorn"},
    {name = "Mostafa Hadavand"},
    {name = "Ryan Barnett"},
]
maintainers = [
    {name = "pygeostat development team", email = "hadavand@ualberta.ca"},
]
description = "Python interface for geostatistics"
readme = "README.md"
keywords = ["geostatistics"]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"

[project.optional-dependencies]
docs = [
    "sphinx",
    "nbsphinx",
    "sphinx-rtd-theme"
]
dev = [
    "pytest",
    "ruff",
]


[project.urls]
Documentation = "https://www.ccgalberta.com/pygeostat/welcome.html"
Source = "https://github.com/CcgAlberta/pygeostat"

[tool.setuptools.packages.find]
where = ["src"]
include = [
    "pygeostat",
    "pygeostat.*",
]

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
version = {attr = "pygeostat.__version__"}
