/* File: pygsbmodule.c
 * This file is auto-generated with f2py (version:1.20.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Nov 10 02:49:32 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *pygsb_error;
static PyObject *pygsb_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(pygsb_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess)
{
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyBytes_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyBytes_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyBytes_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = pygsb_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj, 0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = pygsb_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = pygsb_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(pyreadgsbheader,PYREADGSBHEADER)(string,int*,int*,int*,int*,int*,int*,size_t);
extern void F_FUNC(pyreadgsbdata,PYREADGSBDATA)(string,int*,int*,int*,double*,int*,double*,string*,size_t);
extern void F_FUNC(pywritegsbdata,PYWRITEGSBDATA)(string,double*,string*,int*,int*,int*,int*,int*,double*,double*,int*,int*,int*,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** pyreadgsbheader ******************************/
static char doc_f2py_rout_pygsb_pyreadgsbheader[] = "\
nvar,nx,ny,nz,nreal,errorvalue = pyreadgsbheader(gsbfl)\n\nWrapper for ``pyreadgsbheader``.\
\n\nParameters\n----------\n"
"gsbfl : input string(len=512)\n"
"\nReturns\n-------\n"
"nvar : int\n"
"nx : int\n"
"ny : int\n"
"nz : int\n"
"nreal : int\n"
"errorvalue : int";
/* extern void F_FUNC(pyreadgsbheader,PYREADGSBHEADER)(string,int*,int*,int*,int*,int*,int*,size_t); */
static PyObject *f2py_rout_pygsb_pyreadgsbheader(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,int*,int*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  string gsbfl = NULL;
  int slen(gsbfl);
  PyObject *gsbfl_capi = Py_None;
  int nvar = 0;
  int nx = 0;
  int ny = 0;
  int nz = 0;
  int nreal = 0;
  int errorvalue = 0;
    static char *capi_kwlist[] = {"gsbfl",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:pygsb.pyreadgsbheader",\
        capi_kwlist,&gsbfl_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable gsbfl */
  slen(gsbfl) = 512;
  f2py_success = string_from_pyobj(&gsbfl,&slen(gsbfl),"",gsbfl_capi,"string_from_pyobj failed in converting 1st argument `gsbfl' of pygsb.pyreadgsbheader to C string");
  if (f2py_success) {
  /* Processing variable nvar */
  /* Processing variable nx */
  /* Processing variable ny */
  /* Processing variable nz */
  /* Processing variable nreal */
  /* Processing variable errorvalue */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(gsbfl,&nvar,&nx,&ny,&nz,&nreal,&errorvalue,slen(gsbfl));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iiiiii",nvar,nx,ny,nz,nreal,errorvalue);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable errorvalue */
  /* End of cleaning variable nreal */
  /* End of cleaning variable nz */
  /* End of cleaning variable ny */
  /* End of cleaning variable nx */
  /* End of cleaning variable nvar */
    STRINGFREE(gsbfl);
  }  /*if (f2py_success) of gsbfl*/
  /* End of cleaning variable gsbfl */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of pyreadgsbheader ***************************/

/******************************* pyreadgsbdata *******************************/
static char doc_f2py_rout_pygsb_pyreadgsbdata[] = "\
errorvalue,datamat,vnames = pyreadgsbdata(gsbfl,nvar,nxyz,ireal,nullval)\n\nWrapper for ``pyreadgsbdata``.\
\n\nParameters\n----------\n"
"gsbfl : input string(len=512)\n"
"nvar : input int\n"
"nxyz : input int\n"
"ireal : input int\n"
"nullval : input float\n"
"\nReturns\n-------\n"
"errorvalue : int\n"
"datamat : rank-2 array('d') with bounds (nvar,nxyz)\n"
"vnames : rank-2 array('S') with bounds (nvar,64)";
/* extern void F_FUNC(pyreadgsbdata,PYREADGSBDATA)(string,int*,int*,int*,double*,int*,double*,string*,size_t); */
static PyObject *f2py_rout_pygsb_pyreadgsbdata(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,int*,double*,int*,double*,string*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  string gsbfl = NULL;
  int slen(gsbfl);
  PyObject *gsbfl_capi = Py_None;
  int nvar = 0;
  PyObject *nvar_capi = Py_None;
  int nxyz = 0;
  PyObject *nxyz_capi = Py_None;
  int ireal = 0;
  PyObject *ireal_capi = Py_None;
  double nullval = 0;
  PyObject *nullval_capi = Py_None;
  int errorvalue = 0;
  double *datamat = NULL;
  npy_intp datamat_Dims[2] = {-1, -1};
  const int datamat_Rank = 2;
  PyArrayObject *capi_datamat_tmp = NULL;
  int capi_datamat_intent = 0;
  string *vnames = NULL;
  npy_intp vnames_Dims[2] = {-1, -1};
  const int vnames_Rank = 2;
  PyArrayObject *capi_vnames_tmp = NULL;
  int capi_vnames_intent = 0;
    static char *capi_kwlist[] = {"gsbfl","nvar","nxyz","ireal","nullval",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|:pygsb.pyreadgsbdata",\
        capi_kwlist,&gsbfl_capi,&nvar_capi,&nxyz_capi,&ireal_capi,&nullval_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable gsbfl */
  slen(gsbfl) = 512;
  f2py_success = string_from_pyobj(&gsbfl,&slen(gsbfl),"",gsbfl_capi,"string_from_pyobj failed in converting 1st argument `gsbfl' of pygsb.pyreadgsbdata to C string");
  if (f2py_success) {
  /* Processing variable nxyz */
    f2py_success = int_from_pyobj(&nxyz,nxyz_capi,"pygsb.pyreadgsbdata() 3rd argument (nxyz) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nvar */
    f2py_success = int_from_pyobj(&nvar,nvar_capi,"pygsb.pyreadgsbdata() 2nd argument (nvar) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ireal */
    f2py_success = int_from_pyobj(&ireal,ireal_capi,"pygsb.pyreadgsbdata() 4th argument (ireal) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nullval */
    f2py_success = double_from_pyobj(&nullval,nullval_capi,"pygsb.pyreadgsbdata() 5th argument (nullval) can't be converted to double");
  if (f2py_success) {
  /* Processing variable errorvalue */
  /* Processing variable datamat */
  datamat_Dims[0]=nvar,datamat_Dims[1]=nxyz;
  capi_datamat_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_datamat_tmp = array_from_pyobj(NPY_DOUBLE,datamat_Dims,datamat_Rank,capi_datamat_intent,Py_None);
  if (capi_datamat_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : pygsb_error,"failed in converting hidden `datamat' of pygsb.pyreadgsbdata to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    datamat = (double *)(PyArray_DATA(capi_datamat_tmp));

  /* Processing variable vnames */
  vnames_Dims[0]=nvar,vnames_Dims[1]=64;
  capi_vnames_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
  capi_vnames_tmp = array_from_pyobj(NPY_STRING,vnames_Dims,vnames_Rank,capi_vnames_intent,Py_None);
  if (capi_vnames_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : pygsb_error,"failed in converting hidden `vnames' of pygsb.pyreadgsbdata to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    vnames = (string *)(PyArray_DATA(capi_vnames_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(gsbfl,&nvar,&nxyz,&ireal,&nullval,&errorvalue,datamat,vnames,slen(gsbfl));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iNN",errorvalue,capi_datamat_tmp,capi_vnames_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_vnames_tmp == NULL) ... else of vnames*/
  /* End of cleaning variable vnames */
  }  /*if (capi_datamat_tmp == NULL) ... else of datamat*/
  /* End of cleaning variable datamat */
  /* End of cleaning variable errorvalue */
  } /*if (f2py_success) of nullval*/
  /* End of cleaning variable nullval */
  } /*if (f2py_success) of ireal*/
  /* End of cleaning variable ireal */
  } /*if (f2py_success) of nvar*/
  /* End of cleaning variable nvar */
  } /*if (f2py_success) of nxyz*/
  /* End of cleaning variable nxyz */
    STRINGFREE(gsbfl);
  }  /*if (f2py_success) of gsbfl*/
  /* End of cleaning variable gsbfl */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of pyreadgsbdata ****************************/

/******************************* pywritegsbdata *******************************/
static char doc_f2py_rout_pygsb_pywritegsbdata[] = "\
errorvalue = pywritegsbdata(gsbfl,datamat,vnames,nreal,nx,ny,nz,tmin,tmax,tvar,vkinds,[nvar])\n\nWrapper for ``pywritegsbdata``.\
\n\nParameters\n----------\n"
"gsbfl : input string(len=512)\n"
"datamat : input rank-2 array('d') with bounds (nvar,nreal*nx*ny*nz)\n"
"vnames : input rank-2 array('S') with bounds (nvar,64)\n"
"nreal : input int\n"
"nx : input int\n"
"ny : input int\n"
"nz : input int\n"
"tmin : input float\n"
"tmax : input float\n"
"tvar : input int\n"
"vkinds : input rank-1 array('i') with bounds (nvar)\n"
"\nOther Parameters\n----------------\n"
"nvar : input int, optional\n    Default: shape(datamat,0)\n"
"\nReturns\n-------\n"
"errorvalue : int";
/* extern void F_FUNC(pywritegsbdata,PYWRITEGSBDATA)(string,double*,string*,int*,int*,int*,int*,int*,double*,double*,int*,int*,int*,size_t); */
static PyObject *f2py_rout_pygsb_pywritegsbdata(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,double*,string*,int*,int*,int*,int*,int*,double*,double*,int*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  string gsbfl = NULL;
  int slen(gsbfl);
  PyObject *gsbfl_capi = Py_None;
  double *datamat = NULL;
  npy_intp datamat_Dims[2] = {-1, -1};
  const int datamat_Rank = 2;
  PyArrayObject *capi_datamat_tmp = NULL;
  int capi_datamat_intent = 0;
  PyObject *datamat_capi = Py_None;
  string *vnames = NULL;
  npy_intp vnames_Dims[2] = {-1, -1};
  const int vnames_Rank = 2;
  PyArrayObject *capi_vnames_tmp = NULL;
  int capi_vnames_intent = 0;
  PyObject *vnames_capi = Py_None;
  int nvar = 0;
  PyObject *nvar_capi = Py_None;
  int nreal = 0;
  PyObject *nreal_capi = Py_None;
  int nx = 0;
  PyObject *nx_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz = 0;
  PyObject *nz_capi = Py_None;
  double tmin = 0;
  PyObject *tmin_capi = Py_None;
  double tmax = 0;
  PyObject *tmax_capi = Py_None;
  int tvar = 0;
  PyObject *tvar_capi = Py_None;
  int *vkinds = NULL;
  npy_intp vkinds_Dims[1] = {-1};
  const int vkinds_Rank = 1;
  PyArrayObject *capi_vkinds_tmp = NULL;
  int capi_vkinds_intent = 0;
  PyObject *vkinds_capi = Py_None;
  int errorvalue = 0;
    static char *capi_kwlist[] = {"gsbfl","datamat","vnames","nreal","nx","ny","nz","tmin","tmax","tvar","vkinds","nvar",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOO|O:pygsb.pywritegsbdata",\
        capi_kwlist,&gsbfl_capi,&datamat_capi,&vnames_capi,&nreal_capi,&nx_capi,&ny_capi,&nz_capi,&tmin_capi,&tmax_capi,&tvar_capi,&vkinds_capi,&nvar_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable gsbfl */
  slen(gsbfl) = 512;
  f2py_success = string_from_pyobj(&gsbfl,&slen(gsbfl),"",gsbfl_capi,"string_from_pyobj failed in converting 1st argument `gsbfl' of pygsb.pywritegsbdata to C string");
  if (f2py_success) {
  /* Processing variable nx */
    f2py_success = int_from_pyobj(&nx,nx_capi,"pygsb.pywritegsbdata() 5th argument (nx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ny */
    f2py_success = int_from_pyobj(&ny,ny_capi,"pygsb.pywritegsbdata() 6th argument (ny) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nz */
    f2py_success = int_from_pyobj(&nz,nz_capi,"pygsb.pywritegsbdata() 7th argument (nz) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nreal */
    f2py_success = int_from_pyobj(&nreal,nreal_capi,"pygsb.pywritegsbdata() 4th argument (nreal) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tvar */
    f2py_success = int_from_pyobj(&tvar,tvar_capi,"pygsb.pywritegsbdata() 10th argument (tvar) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tmin */
    f2py_success = double_from_pyobj(&tmin,tmin_capi,"pygsb.pywritegsbdata() 8th argument (tmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tmax */
    f2py_success = double_from_pyobj(&tmax,tmax_capi,"pygsb.pywritegsbdata() 9th argument (tmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable errorvalue */
  /* Processing variable datamat */
  datamat_Dims[1]=nreal*nx*ny*nz;
  capi_datamat_intent |= F2PY_INTENT_IN;
  capi_datamat_tmp = array_from_pyobj(NPY_DOUBLE,datamat_Dims,datamat_Rank,capi_datamat_intent,datamat_capi);
  if (capi_datamat_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : pygsb_error,"failed in converting 2nd argument `datamat' of pygsb.pywritegsbdata to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    datamat = (double *)(PyArray_DATA(capi_datamat_tmp));

  /* Processing variable nvar */
  if (nvar_capi == Py_None) nvar = shape(datamat,0); else
    f2py_success = int_from_pyobj(&nvar,nvar_capi,"pygsb.pywritegsbdata() 1st keyword (nvar) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(datamat,0)==nvar,"shape(datamat,0)==nvar","1st keyword nvar","pywritegsbdata:nvar=%d",nvar) {
  /* Processing variable vkinds */
  vkinds_Dims[0]=nvar;
  capi_vkinds_intent |= F2PY_INTENT_IN;
  capi_vkinds_tmp = array_from_pyobj(NPY_INT,vkinds_Dims,vkinds_Rank,capi_vkinds_intent,vkinds_capi);
  if (capi_vkinds_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : pygsb_error,"failed in converting 11st argument `vkinds' of pygsb.pywritegsbdata to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    vkinds = (int *)(PyArray_DATA(capi_vkinds_tmp));

  /* Processing variable vnames */
  vnames_Dims[0]=nvar,vnames_Dims[1]=64;
  capi_vnames_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_vnames_tmp = array_from_pyobj(NPY_STRING,vnames_Dims,vnames_Rank,capi_vnames_intent,vnames_capi);
  if (capi_vnames_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : pygsb_error,"failed in converting 3rd argument `vnames' of pygsb.pywritegsbdata to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    vnames = (string *)(PyArray_DATA(capi_vnames_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(gsbfl,datamat,vnames,&nvar,&nreal,&nx,&ny,&nz,&tmin,&tmax,&tvar,vkinds,&errorvalue,slen(gsbfl));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",errorvalue);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vnames_tmp!=vnames_capi) {
    Py_XDECREF(capi_vnames_tmp); }
  }  /*if (capi_vnames_tmp == NULL) ... else of vnames*/
  /* End of cleaning variable vnames */
  if((PyObject *)capi_vkinds_tmp!=vkinds_capi) {
    Py_XDECREF(capi_vkinds_tmp); }
  }  /*if (capi_vkinds_tmp == NULL) ... else of vkinds*/
  /* End of cleaning variable vkinds */
  } /*CHECKSCALAR(shape(datamat,0)==nvar)*/
  } /*if (f2py_success) of nvar*/
  /* End of cleaning variable nvar */
  if((PyObject *)capi_datamat_tmp!=datamat_capi) {
    Py_XDECREF(capi_datamat_tmp); }
  }  /*if (capi_datamat_tmp == NULL) ... else of datamat*/
  /* End of cleaning variable datamat */
  /* End of cleaning variable errorvalue */
  } /*if (f2py_success) of tmax*/
  /* End of cleaning variable tmax */
  } /*if (f2py_success) of tmin*/
  /* End of cleaning variable tmin */
  } /*if (f2py_success) of tvar*/
  /* End of cleaning variable tvar */
  } /*if (f2py_success) of nreal*/
  /* End of cleaning variable nreal */
  } /*if (f2py_success) of nz*/
  /* End of cleaning variable nz */
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  } /*if (f2py_success) of nx*/
  /* End of cleaning variable nx */
    STRINGFREE(gsbfl);
  }  /*if (f2py_success) of gsbfl*/
  /* End of cleaning variable gsbfl */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of pywritegsbdata ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"pyreadgsbheader",-1,{{-1}},0,(char *)F_FUNC(pyreadgsbheader,PYREADGSBHEADER),(f2py_init_func)f2py_rout_pygsb_pyreadgsbheader,doc_f2py_rout_pygsb_pyreadgsbheader},
  {"pyreadgsbdata",-1,{{-1}},0,(char *)F_FUNC(pyreadgsbdata,PYREADGSBDATA),(f2py_init_func)f2py_rout_pygsb_pyreadgsbdata,doc_f2py_rout_pygsb_pyreadgsbdata},
  {"pywritegsbdata",-1,{{-1}},0,(char *)F_FUNC(pywritegsbdata,PYWRITEGSBDATA),(f2py_init_func)f2py_rout_pygsb_pywritegsbdata,doc_f2py_rout_pygsb_pywritegsbdata},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "pygsb",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_pygsb(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = pygsb_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module pygsb (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("1.20.3");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'pygsb' is auto-generated with f2py (version:1.20.3).\nFunctions:\n"
"  nvar,nx,ny,nz,nreal,errorvalue = pyreadgsbheader(gsbfl)\n"
"  errorvalue,datamat,vnames = pyreadgsbdata(gsbfl,nvar,nxyz,ireal,nullval)\n"
"  errorvalue = pywritegsbdata(gsbfl,datamat,vnames,nreal,nx,ny,nz,tmin,tmax,tvar,vkinds,nvar=shape(datamat,0))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.20.3");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  pygsb_error = PyErr_NewException ("pygsb.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_pygsb_error", pygsb_error);
  Py_DECREF(pygsb_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"pygsb");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
